ci: add component tests to pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,6 +75,36 @@ jobs:
           path: ./TestResults/Unit
           retention-days: 7
 
+  component-tests:
+    name: Run Component Tests
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.x'
+
+      - name: Run Component Tests
+        run: |
+          set -e
+          echo "🚀 Running all Component Tests..."
+          dotnet test $SOLUTION_FILE \
+            --configuration Release \
+            --logger:"trx" \
+            --results-directory ./TestResults \
+            --filter "FullyQualifiedName~ComponentTests"
+                
+      - name: Upload Test Results
+        if: failure()  # Only upload if the tests failed
+        uses: actions/upload-artifact@v4
+        with:
+          name: component-test-results
+          path: ./TestResults/Component
+          retention-days: 7
+
   integration-tests:
     name: Run Integration
     runs-on: ubuntu-latest
